export const defaultRowsPerView = 5;
export const defaultPage = 0;

export const HEADER = {
	ticketType: 'Ticket Type',
	ticketNumber: 'Ticket Number',
	ticketSummary: 'Ticket Summary',
	assignee: 'Assignee',
	reporter: 'Reporter',
	priority: 'Priority',
	status: 'Status',
	estimate: 'Estimate',
};

export const TABLE_DATA = [
	{
		ticketType: 'Bug',
		ticketNumber: 1,
		ticketSummary: '',
		assignee: 'unassigned',
		reporter: 'user1',
		priority: 'blocker',
		status: 'open',
		estimate: '0',
	},
	{
		ticketType: 'User Story',
		ticketNumber: 2,
		ticketSummary: '',
		assignee: 'unassigned',
		reporter: 'user1',
		priority: 'blocker',
		status: 'open',
		estimate: '0',
	},
	{
		ticketType: 'Bug',
		ticketNumber: 3,
		ticketSummary: '',
		assignee: 'unassigned',
		reporter: 'user1',
		priority: 'blocker',
		status: 'open',
		estimate: '0',
	},
	{
		ticketType: 'Epic',
		ticketNumber: 4,
		ticketSummary: '',
		assignee: 'unassigned',
		reporter: 'user1',
		priority: 'blocker',
		status: 'open',
		estimate: '0',
	},

	{
		ticketType: 'Bug',
		ticketNumber: 5,
		ticketSummary: '',
		assignee: 'unassigned',
		reporter: 'user1',
		priority: 'blocker',
		status: 'open',
		estimate: '0',
	},
	{
		ticketType: 'Epic',
		ticketNumber: 6,
		ticketSummary: '',
		assignee: 'unassigned',
		reporter: 'user2',
		priority: 'blocker',
		status: 'open',
		estimate: '0',
	},
	{
		ticketType: 'Task',
		ticketNumber: 7,
		ticketSummary: '',
		assignee: 'unassigned',
		reporter: 'user2',
		priority: 'blocker',
		status: 'open',
		estimate: '0',
	},
	{
		ticketType: 'Epic',
		ticketNumber: 8,
		ticketSummary: '',
		assignee: 'unassigned',
		reporter: 'user1',
		priority: 'blocker',
		status: 'open',
		estimate: '0',
	},
	{
		ticketType: 'User Story',
		ticketNumber: 9,
		ticketSummary: '',
		assignee: 'unassigned',
		reporter: 'user3',
		priority: 'blocker',
		status: 'open',
		estimate: '0',
	},
	{
		ticketType: 'User Story',
		ticketNumber: 10,
		ticketSummary: '',
		assignee: 'unassigned',
		reporter: 'user3',
		priority: 'blocker',
		status: 'open',
		estimate: '0',
	},
];
