export const TABLE_DATA = [
	{
		ticketType: 'Bug',
		ticketNumber: 1,
		ticketSummary: '',
		assignee: 'unassigned',
		reporter: 'user2',
		priority: 'medium',
		status: 'in progress',
		estimate: '8h',
	},
	{
		ticketType: 'User Story',
		ticketNumber: 2,
		ticketSummary: '',
		assignee: 'unassigned',
		reporter: 'user1',
		priority: 'blocker',
		status: 'open',
		estimate: '0',
	},
	{
		ticketType: 'Bug',
		ticketNumber: 3,
		ticketSummary: '',
		assignee: 'unassigned',
		reporter: 'user1',
		priority: 'critical',
		status: 'open',
		estimate: '0',
	},
	{
		ticketType: 'Epic',
		ticketNumber: 4,
		ticketSummary: '',
		assignee: 'user3',
		reporter: 'user1',
		priority: 'minor',
		status: 'closed',
		estimate: '1h',
	},

	{
		ticketType: 'Bug',
		ticketNumber: 5,
		ticketSummary: '',
		assignee: 'unassigned',
		reporter: 'user1',
		priority: 'blocker',
		status: 'in progress',
		estimate: '1h',
	},
	{
		ticketType: 'Epic',
		ticketNumber: 6,
		ticketSummary: '',
		assignee: 'user1',
		reporter: 'user2',
		priority: 'blocker',
		status: 'open',
		estimate: '0',
	},
	{
		ticketType: 'Task',
		ticketNumber: 7,
		ticketSummary: '',
		assignee: 'unassigned',
		reporter: 'user2',
		priority: 'minor',
		status: 'in progress',
		estimate: '8',
	},
	{
		ticketType: 'Epic',
		ticketNumber: 8,
		ticketSummary: '',
		assignee: 'unassigned',
		reporter: 'user1',
		priority: 'blocker',
		status: 'open',
		estimate: '0',
	},
	{
		ticketType: 'User Story',
		ticketNumber: 9,
		ticketSummary: '',
		assignee: 'unassigned',
		reporter: 'user3',
		priority: 'blocker',
		status: 'open',
		estimate: '0.5h',
	},
	{
		ticketType: 'User Story',
		ticketNumber: 10,
		ticketSummary: '',
		assignee: 'user1',
		reporter: 'user3',
		priority: 'critical',
		status: 'open',
		estimate: '2h',
	},
];
